---
apiVersion: v1
kind: Pod
metadata:
  name: all
  labels:
    aeronmd: java
spec:
  containers:
    - name: aeronmd-java
      imagePullPolicy: Always
      command: ["/opt/aeron-benchmarks/scripts/k8s/k8s-java-media-driver.sh"]
      volumeMounts:
        - name: shm
          mountPath: /dev/shm
      resources:
        limits:
          cpu: "8"
          memory: 8G
