# Base deployment - do not apply this, use the specific deployments in the other subdirectories

resources:
  - k8s-benchmark.yml
  - extra-objects.yml
patches:
  # Standard config for all the pods
  - path: base-containers.yml
    target:
      kind: Pod

  # Aeron echo specific config
  - path: echo-server.yml
    target:
      kind: Pod
      name: aeron-benchmark-0

  - path: settings.yml
    target:
      kind: Pod

  # allow passing anything basically.
  - path: extra-objects.yml
